apiVersion: v1
kind: Secret
metadata:
  labels:
    app: jn-quarkus-base
    group: com.javanes.micro
    provider: javanes
  name: gs-jn-quarkus-base
data:
  secret-key-1: c2VjcmV0LXZhbHVlLTE=
  secret-key-2: c2VjcmV0LXZhbHVlLTI=
